### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by NickRimmer** [RestApia/RestApia.Community#1]
## Roadmap

We’re committed to adapting and evolving based on feedback, so while we don't have fixed dates, we focus on delivering high-priority features that meet your needs. Here are the current top priorities:

- [x] **Application settings**: Requests configuration, General settings, User account
- [x] **Extension Support**: Allowing users to expand the app’s capabilities with custom and official extensions.
- [ ] **Basic Online Services**: Introducing foundational online features that will enable access to extensions and other upcoming services.
- [ ] Multiple endpoints in one request item support (show multiple responses)
- [x] Better values provider settings editor
- [ ] Cache values (e.g. Authorization headers) per environment
- [ ] More interactive request path in request view. Add context menu for path elements. On path element click, expand (if folder) and focus in collection list
- [ ] Extension updates. Make it possible to receive information about updates and apply them
- [x] Remember request view settings (size, last opened response tab)
- [x] Change requests serialization to more friendly format for git
- [x] Quick search dialog for better access to requests

---

Your ideas play a crucial role in shaping the future of **RestApia**, so please don’t hesitate to share your thoughts.
